onlinemarket/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static 
from market import views as marketViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('customer/', include('customer.urls')),
    path('vendor/', include('vendor.urls')),
    path('market/', include('market.urls')),
    path('', include('flashsale.urls')),

    #cart
    path('cart/', marketViews.cart, name='cart'),

    path('checkout/', marketViews.checkout, name='checkout'),

    path('search/', marketViews.search, name='search'),

    path('order/', include('order.urls')),

    path('postsharing/', include('postsharing.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.place_order, name='place_order'),
    path('make_payment/', views.make_payment, name='make_payment'),
    
    path('payment_complete/', views.payment_complete, name='payment_complete'),
]

accounts/models.py
from enum import Enum
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager 
from django.db.models.fields.related import OneToOneField
from django.contrib.gis.db import models as gismodels
from django.contrib.gis.geos import Point
from django.urls import reverse

# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not username:
            raise ValueError('User must have an username')
        if not email:
            raise ValueError('User must have an email')
        user = self.model(
            username = username,
            email = self.normalize_email(email)
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, username, email, password=None):
        user = self.create_user(
            email = email,
            username = username,
            password = password,
        )
        user.is_admin = True
        user.is_active = True
        user.save(using=self._db)
        return user
    

class User(AbstractBaseUser):

    class Role(models.IntegerChoices):
        VENDOR = 1, ('Vendor') 
        CUSTOMER = 2, ('Customer') 

    first_name = models.CharField(max_length=20, blank=True, null=True)
    last_name = models.CharField(max_length=20, blank=True, null=True)
    username = models.CharField(max_length=20, unique=True)
    email = models.EmailField(max_length=50)
    is_active = models.BooleanField(default=False)
    phone = models.CharField(max_length=15, blank=True, null=True)
    role = models.PositiveSmallIntegerField(choices=Role.choices, blank=True, null=True)

    #Required fields
    is_admin = models.BooleanField(default=False)
    last_login = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
  


    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    def __str__(self):
        return self.username
    
    def get_role(self):
        user_role = ''
        if self.role == 1:
            user_role = 'Vendor'
        elif self.role == 2:
            user_role = 'Customer'
        return user_role
    
    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True
    
    def get_absolute_url(self):
        return reverse('user_page', args=[str(self.id)]) # type: ignore
    
    @property
    def is_staff(self):
        return self.is_admin
    
class UserProfile(models.Model):
    user = OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True, related_name='profile')
    user_pic = models.ImageField(upload_to='users/user_profiles', blank=True, null=True)
    
    cover_photo = models.ImageField(upload_to='users/cover_photos', blank=True, null=True)
    address = models.CharField(max_length=250, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=50, blank=True, null=True)
    country = models.CharField(max_length=50, blank=True, null=True)
    zip_code = models.CharField(max_length=20, blank=True, null=True)
    location = gismodels.PointField(blank=True, null=True, srid=4326)
    latitude = models.CharField(max_length=20, blank=True, null=True)
    longitude = models.CharField(max_length=20, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.user.username
    
    def save(self, *args, **kwargs):
        if self.latitude and self.longitude:
            self.location = Point(float(self.longitude), float(self.latitude))
        return super(UserProfile, self).save(*args, **kwargs)
    

order/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey
from accounts.models import User
from vendor.models import Product, Vendor
import simplejson as json
import logging

logger = logging.getLogger(__name__)

# Create your models here.
request_object = ''
class Payment(models.Model):
    payment_no = models.CharField(max_length=50, unique=True)
    method = models.CharField(max_length=20)
    customer = ForeignKey(User, on_delete=models.CASCADE)
    amount = models.FloatField()
    status = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.payment_no
    
class Order(models.Model):

    class Status(models.TextChoices):
        NEW = ('New', 'New')
        ACCEPTED = ('Accepted', 'Accepted')
        COMPLETED = ('Completed', 'Completed')
        CANCELED = ('Canceled', 'Canceled')

    order_no = models.CharField(max_length=50, unique=True)
    customer = ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    vendors = models.ManyToManyField(Vendor, blank=True)
    first_name = models.CharField(max_length=20, blank=True, null=True)
    last_name = models.CharField(max_length=20, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=20, blank=True, null=True)
    state = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=20, blank=True, null=True)
    zip_code = models.CharField(max_length=20, blank=True, null=True)

    first_name_bill = models.CharField(max_length=20, blank=True, null=True)
    last_name_bill = models.CharField(max_length=20, blank=True, null=True)
    phone_bill = models.CharField(max_length=20, blank=True, null=True)
    email_bill = models.EmailField(max_length=50, blank=True, null=True)
    address_bill = models.CharField(max_length=50, blank=True, null=True)
    city_bill = models.CharField(max_length=20, blank=True, null=True)
    state_bill = models.CharField(max_length=20, blank=True, null=True)
    country_bill = models.CharField(max_length=20, blank=True, null=True)
    zip_code_bill = models.CharField(max_length=20, blank=True, null=True)

    sub_amount = models.FloatField()
    tax_amount = models.FloatField()
    tax_data = models.JSONField(blank=True, null=True, help_text="Data format: 'tax_type': {{'percentage': 'tax_amount'}}")
    total_amount = models.FloatField()
    total_data = models.JSONField(blank=True, null=True)
    status = models.CharField(max_length=15, choices=Status.choices, default='New')
    payment = ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    payment_method = models.CharField(max_length=20, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.order_no
    
    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'
    
    def order_to_vendors(self):
        return ','.join([str(i) for i in self.vendors.all()])
    
    def get_total_by_vendor(self):
        vendor = Vendor.objects.get(user=request_object.user) # type: ignore
        subtotal = 0
        tax = 0
        total = 0
        tax_dict = {}
        try:
            total_dict =  json.loads(self.total_data) if self.total_data else {}
            data = total_dict[str(vendor.pk)]
            for key, val in data.items():
                subtotal += float(key)
                tax_dict.update(val)
                for type, value in val.items():
                    for i, j in value.items():
                        tax += j
        except Exception as e:
            logger.error(e)
            total = 0
        total = subtotal + tax

        return {
            'subtotal': subtotal,
            'tax': tax,
            'tax_dict': tax_dict,
            'total': total,
        }

    
class OrderedItem(models.Model):
    product = ForeignKey(Product, on_delete=models.CASCADE)
    price = models.FloatField()
    quantity = models.IntegerField()
    amount = models.FloatField()
    customer = ForeignKey(User, on_delete=models.CASCADE)
    order = ForeignKey(Order, on_delete=models.CASCADE)
    payment = ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>OnlineMarket</title>
    <!-- Google Font Family Link Start -->
    <link
      rel="stylesheet"
      type="text/css"
      href="https://fonts.googleapis.com/css?family=Montserrat:400,700"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800"
    />
    <!-- Google Font Family Link End -->

    <!-- CSS -->
    <link href="{% static '/css/iconmoon.css' %}" rel="stylesheet" />
    <link href="{% static '/css/style.css' %}" rel="stylesheet" />
    <link href="{% static '/css/cs-foodbakery-plugin.css'%}" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static '/css/bootstrap-slider.css' %}" rel="stylesheet" />


    <!-- JAVASCRIPT -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    
    <script src="{% static '/js/modernizr.js' %}"></script>
    <script src="{% static '/js/bootstrap.js' %}"></script>
    <link rel="stylesheet" href="{% static '/css/custom.css' %}" class="stylesheet">
    <script src="{% static '/js/custom.js' %}"></script>

    <!-- Google API -->
    {% if '/' == request.path or 'profile' in request.path %}
    <script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete" defer></script>
    {% endif %}
    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id={{ PAYPAL_CLIENT_ID }}&currency=USD"></script>

    <!-- Include Datatables plugin script and css -->
	  <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
	  <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
	  <script>
		$(document).ready( function () {
			$('#myOrdersTable').DataTable();
		} );
	  </script>
    
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.css' rel='stylesheet' />


    <style>
      body,
      .main-section p,
      .mce-content-body p {
        font: Normal 14px/24px "Open Sans", sans-serif;
        letter-spacing: 0px;
        text-transform: none;
        color: #515151 !important;
    </style>
  </head>

  <body>
    {% include 'includes/nav.html' %} 
    {% block content %}
    {% endblock %} 
    {% include 'includes/alert.html' %}
    {% include 'includes/footer.html' %}

templates/boilerplate.html
<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Post sharing</title>
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendor/font-awesome-4.6.3/css/font-awesome.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>
    <body>

        {% load static %}
        {% include 'includes/header.html' %}
        
        <div class="content-wrapper">
            <div class="container">
                {% include 'includes/alert.html' %}
                {% block content %}
                {% endblock content%}
            </div>
            
        </div>

        <script type="text/javascript" src="{% static 'vendor/jquery-3.1.0.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
        <!-- <script type="text/javascript" src="{% static 'js/ajax-csrf-auth.js' %}"></script> -->
        <script type="text/javascript" src="{% static 'js/index.js' %}"></script>

        {% block extrascript %}
        {% endblock %}

    </body>

</html>
    

templates/home.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<div class="main-section">
  

  <!-- Home Pages Elements Strat -->
  <!-- Main Search Start -->
  <div
    class="page-section nopadding cs-nomargin main-search-bar"
    style="
      padding-top: 200px;
      padding-bottom: 0px;
      margin-bottom: 0px;
      background: url(static/extra-images/main-logo.jpg) no-repeat center /
        cover;
    "
  >
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="element-title">
            <h1
              style="
                font-size: 40px;
                color: #505050;
                text-transform: uppercase;
                line-height: 50px;
                margin-bottom: 25px;
                text-align: center;
              "
            >
              We serve for customers and small businesses!<br />
            </h1>
            <p
              style="
                font-size: 18px;
                letter-spacing: 1px;
                color: #505050;
                text-align: center;
              "
            >
              Please search using vendor or product name you want.
            </p>
          </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="main-search fancy bg-holder">
            <form action="{% url 'search' %}" method="GET">
              <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
                  <div class="field-holder">
                    <input type="text" name="keyword" placeholder="Vendor or product name" />
                  </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
                  <div class="field-holder">
                    <li class="select-location">
                    <div class="foodbakery-locations-fields-group foodbakery-focus-out">
                    <span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
                    <input type="text" name="address" id="id_address" placeholder="Address" required/>
                    <input type="hidden" name="lat" value="" id="id_latitude">
										<input type="hidden" name="lng" value="" id="id_longitude">
                    </div>
                    </li>
                  </div>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                  <select name="radius" id="radius" style="height: 50px;" required>
                    <option value="" selected>Choose Radius</option>
                    <option value="5">5 km</option>
                    <option value="10">10 km</option>
                    <option value="15">15 km</option>
                    <option value="25">25 km</option>
                    <option value="50">50 km</option>
                    <option value="100">100 km</option>
                  </select>
                </div>
                
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                  <div class="field-holder">
                    <input type="submit" value="Search" />
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
    

  <!-- Main Search End -->

  <!-- Top Restarurants Section Start -->
  <div
    class="page-section nopadding cs-nomargin"
    style="
      margin-top: 0px;
      padding-top: 30px;
      padding-bottom: 0px;
      margin-bottom: 0px;
      background: #ffffff;
      display: flex;
      justify-content: center;
    "
  >
  
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div id="cluster-map" style="width: 100%; height: 500px;"></div>
          <br>

          <div class="element-title align-left">
            <h2>Top services</h2>
            <p>Explore shops, restaurants, bars, and more</p>
          </div>
        </div>
        <br>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 px-0">
          <div class="company-logo">
            <ul>
              {% for vendor in vendors %}
              <li class="has-border">
                <figure class="wrapper">
                  <a href="{% url 'vendor_detail' vendor.slug_name %}"
                    ><img
                      src="{{vendor.profile.user_pic.url}}"
                      class=""
                      style="object-fit: cover;"
                      alt=""
                  /></a>
                </figure>
              </li>
              {% endfor %}
              
              
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Top Restarurants Section End -->
  <!-- Choose From Most Popular Listin Start -->
  <div
    class="page-section nopadding cs-nomargin"
    style="
      margin-top: 0px;
      padding-top: 60px;
      padding-bottom: 50px;
      margin-bottom: 0px;
      background: #ffffff;
    "
  >
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="element-title align-center">
            <h2>Choose From Most Popular Vendors</h2>
            
          </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="listing fancy">
            <ul class="row">
              {% for vendor in vendors %}
              <li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <div class="list-post featured">
                  <div class="img-holder">
                    <figure>
                      <a href="{% url 'vendor_detail' vendor.slug_name %}"
                        ><img
                          src="{{vendor.profile.user_pic.url}}"
                          class="img-thumb wp-post-image"
                          alt=""
                      /></a>
                    </figure>
                    {% if vendor.is_open %}
                    <span class="restaurant-status open">
                      <em class="bookmarkRibbon"></em>open
                    </span>
                    {% else %}
                    <span class="restaurant-status close">
                      <em class="bookmarkRibbon"></em>closed
                    </span>
                    {% endif %}
                  </div>
                  <div class="text-holder">
                    <div class="list-rating">
                      <div class="rating-star">
                        <span class="rating-box" style="width: 100%"></span>
                      </div>
                      <span class="reviews">(1)</span>
                    </div>
                    <div class="post-title">
                      <h5>
                        <a href="{% url 'vendor_detail' vendor.slug_name %}">{{vendor}}</a>
                        <span class="sponsored text-color">Sponsored</span>
                      </h5>
                      {% if vendor.kms %}
                      <span><small><b>{{vendor.kms}}km</b> from current location</small></span>
                      {% endif %}
                    </div>
                
                  </div>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Choose From Most Popular Listing End -->

  <!-- Home Pages Elements End  -->
</div>

<script>
  const mapToken = '{{MAPBOX_TOKEN}}';
  const profiles_data = {{profiles_json | safe}};
  const vendors_data = {{vendors_json | safe}};
  profiles_data.forEach((profile, i) => {
    profile.geometry = {
      type: 'Point',
      coordinates: [parseFloat(profile.longitude), parseFloat(profile.latitude)]
  }
  profile.type = 'Feature';
  profile.properties = {
    name: vendors_data[i].vendor_name,
    slug_name: vendors_data[i].slug_name
  }
  })
  
  const profiles = {features: profiles_data};
  console.log('before: ', profiles)
  </script>
  <script src="{% static '/js/clusterMap.js' %}"></script>
  
{% endblock %}